services:

  mongo:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="todo"
      - MONGODB_USERNAME="admin"
      - MONGODB_PASSWORD="admin"
    ports:
      - 27017:27017

  mongo-test:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="todo-test"
      - MONGODB_USERNAME="admin"
      - MONGODB_PASSWORD="admin"
    ports:
      - 27018:27017

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
      - mongo-test
    ports:
      - 8081:8081


 

